// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gorilla/mux"
	"github.com/multipleton/shooter/server/http"
	"github.com/multipleton/shooter/server/http/utils"
	"github.com/multipleton/shooter/server/udp"
)

// Injectors from application.go:

func Init(httpServerConfig http.HTTPServerConfig, udpServerConfig udp.UDPServerConfig) (*Application, error) {
	router := mux.NewRouter()
	v := _wireValue
	httpServer := &http.HTTPServer{
		Config:      httpServerConfig,
		Router:      router,
		Controllers: v,
	}
	udpServer := &udp.UDPServer{
		Config: udpServerConfig,
	}
	application := &Application{
		HTTPServer: httpServer,
		UDPServer:  udpServer,
	}
	return application, nil
}

var (
	_wireValue = &[]*utils.HTTPController{}
)

// application.go:

type Application struct {
	HTTPServer *http.HTTPServer
	UDPServer  *udp.UDPServer
}
